#
# File      : SConscript
# This file is part of RT-Thread RTOS/WebNet Server
# COPYRIGHT (C) 2011, Shanghai Real-Thread Technology Co., Ltd
#
# All rights reserved.
#
# Change Logs:
# Date           Author       Notes
# 2011-08-02     Bernard      the first version
#

Import('RTT_ROOT')
from building import *

cmd = os.path.join(GetCurrentDir(), 'src')
src	= Glob('src/*.c')

src_rm = Split("""
tclsqlite.c
test1.c
test2.c
test3.c
test4.c
test5.c
test6.c
test7.c
test8.c
test9.c
test_async.c
test_autoext.c
test_backup.c
test_blob.c
test_btree.c
test_config.c
test_demovfs.c
test_devsym.c
test_fs.c
test_func.c
test_hexio.c
test_init.c
test_intarray.c
test_intarray.h
test_journal.c
test_loadext.c
test_malloc.c
test_multiplex.c
test_multiplex.h
test_mutex.c
test_onefile.c
test_osinst.c
test_pcache.c
test_rtree.c
test_schema.c
test_server.c
test_sqllog.c
test_stat.c
test_superlock.c
test_syscall.c
test_tclvar.c
test_thread.c
test_vfs.c
test_vfstrace.c
test_wsd.c
""")

if GetDepend('SQLITE_TEST') == False:
    SrcRemove(src, src_rm)

CPPPATH = [cmd]
group = DefineGroup('Sqlite', src, depend = ['RT_USING_SQLITE3'], CPPPATH = CPPPATH)

Return('group')
