Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

src = Split("""
romfs.c
platform.c
""")

basedev_src = Split("""
board.c
usart.c
cpuusage.c
""")

basesim_src = Split("""
simbase.c
simusart.c
""")

ethdev_src = Split("""
fec.c
""")

ethsim_src = Split("""
simeth.c
win32/pktdrv.c
""")

rtcdev_src = Split("""
rtc.c
""")

rtcsim_src = Split("""
simrtc.c
""")

nanddev_src = Split("""
nand.c
apbh_dma.c
""")

lcddev_src = Split("""
lcdif.c
mxsfb.c
mxsts.c
""")

if rtconfig.PLATFORM != 'cl':
    src += basedev_src
else:
    src += basesim_src

if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_LWIP']):
        src += ethdev_src
else:
    if GetDepend(['RT_USING_LWIP']):
        src += ethsim_src
    
if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_RTC']):
        src += rtcdev_src
else:
    if GetDepend(['RT_USING_RTC']):
        src += rtcsim_src

if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_MTD_NAND']):
        src += nanddev_src
        
if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_RTGUI']):
        src += lcddev_src

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
