Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

src = Split("""
romfs.c
platform.c
""")

basedev_src = Split("""
board.c
usart.c
nand.c
apbh_dma.c
""")

basesim_src = Split("""
simbase.c
simusart.c
""")

ethdev_src = Split("""
fec.c
""")

ethsim_src = Split("""
simeth.c
win32/pktdrv.c
""")

rtcdev_src = Split("""
devrtc.c
""")

rtcsim_src = Split("""
simrtc.c
""")

spidev_src = Split("""
devspi.c
w25qxx.c
""")

spisim_src = Split("""
simw25qxx.c
""")

elmdev_src = Split("""
w25ftl.c
""")

if rtconfig.PLATFORM != 'cl':
    src += basedev_src
else:
    src += basesim_src

if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_LWIP']):
        src += ethdev_src
else:
    if GetDepend(['RT_USING_LWIP']):
        src += ethsim_src
    
if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_RTC']):
        src += rtcdev_src
else:
    if GetDepend(['RT_USING_RTC']):
        src += rtcsim_src

if rtconfig.PLATFORM != 'cl':
    if GetDepend(['RT_USING_SPI']):
        src += spidev_src
else:
    if GetDepend(['RT_USING_SPI']):
        src += spisim_src

if GetDepend(['RT_USING_DFS_ELMFAT']):
    src += elmdev_src
    
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
