Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

src += Glob('*.S')
group = DefineGroup('IMX6UL', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
