Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = Split("""
""")

# The set of source files associated with this SConscript file.
if rtconfig.PLATFORM == 'armcc':
	src = Glob('*.c') + Glob('*_rvds.S')

if rtconfig.PLATFORM == 'gcc':
	src = Glob('*.c') + Glob('*_gcc.S') + Glob('*_init.S')

if rtconfig.PLATFORM == 'iar':
	src = Glob('*.c') + Glob('*_iar.S')

group = DefineGroup('platform', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
