#
# File      : SConscript
# This file is part of RT-Thread RTOS/WebNet Server
# COPYRIGHT (C) 2011, Shanghai Real-Thread Technology Co., Ltd
#
# All rights reserved.
#
# Change Logs:
# Date           Author       Notes
# 2011-08-02     Bernard      the first version
#

Import('RTT_ROOT')
from building import *

cmd = GetCurrentDir()
generic = Glob('generic/*.c')
libtommath = Glob('libtommath/*.c')
unix = Glob('unix/*.c')

src = generic
src += libtommath
src += unix

src_rm = Split("""
generic/regc_color.c
generic/regc_cvec.c
generic/regc_lex.c
generic/regc_locale.c
generic/regc_nfa.c
generic/rege_dfa.c
""")
SrcRemove(src, src_rm)

CPPPATH = [cmd+'/generic', cmd+'/libtommath', cmd+'/unix']
group = DefineGroup('Sqlite', src, depend = ['RT_USING_SQLITE3'], CPPPATH = CPPPATH)

Return('group')
