# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('RTGUI', src, depend = ['RT_USING_RTGUI','RTGUI_USING_DIALOG'], CPPPATH = CPPPATH)

Return('group')
